name = "ewdev/scheduler"
version = "0.0.0"
description = "A hierarchical, dependency-sorted scheduler for Luau"
authors = ["EwDev (https://ewdev.net/)"]
repository = "https://github.com/ewd3v/luau_scheduler"
license = "MIT"

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"
